language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - sh .travis.install.sh

script:
  - bin/phpspec run --format=pretty
